spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/user?sslMode=VERIFY_IDENTITY
spring.datasource.username=431CNnShADyonte.root
spring.datasource.password=9ObduZ0TAplAZT3R

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
