
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


#Db configation Details file 

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/user?sslMode=VERIFY_IDENTITY
spring.datasource.username=431CNnShADyonte.root
spring.datasource.password=9ObduZ0TAplAZT3R

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver